INSERT INTO Product (name, brand, category, price, description, image_url) VALUES
('iPhone 14', 'Apple', 'SMARTPHONE', 999.99, 'Latest Apple smartphone with A15 chip', 'https://picsum.photos/seed/iphone14/300'),
('Galaxy S22', 'Samsung', 'SMARTPHONE', 899.99, 'Powerful Android device with stunning display', 'https://picsum.photos/seed/galaxys22/300'),
('Pixel 7', 'Google', 'SMARTPHONE', 799.99, 'Clean Android experience from Google', 'https://picsum.photos/seed/pixel7/300'),
('MacBook Air M2', 'Apple', 'LAPTOP', 1199.99, 'Ultra-thin laptop with Apple M2 chip', 'https://picsum.photos/seed/macbookairm2/300'),
('Galaxy Tab S8', 'Samsung', 'TABLET', 699.99, 'High-performance Android tablet with S Pen', 'https://picsum.photos/seed/galaxytabs8/300'),
('ThinkPad X1 Carbon', 'Lenovo', 'LAPTOP', 1299.99, 'Business laptop with robust build and long battery life', 'https://picsum.photos/seed/thinkpadx1/300'),
('iPad Pro', 'Apple', 'TABLET', 999.99, 'Powerful tablet with Apple M2 chip and ProMotion display', 'https://picsum.photos/seed/ipadpro/300'),
('Sony WH-1000XM5', 'Sony', 'HEADPHONES', 399.99, 'Industry-leading noise-canceling headphones', 'https://picsum.photos/seed/sonywh1000xm5/300'),
('AirPods Pro', 'Apple', 'EARBUDS', 249.99, 'Wireless earbuds with active noise cancellation', 'https://picsum.photos/seed/airpodspro/300'),
('Galaxy Buds2 Pro', 'Samsung', 'EARBUDS', 229.99, 'Compact wireless earbuds with ANC', 'https://picsum.photos/seed/galaxybuds2/300'),
('Canon EOS R7', 'Canon', 'CAMERA', 1499.99, 'Mirrorless camera with high-resolution sensor', 'https://picsum.photos/seed/canoneosr7/300'),
('PlayStation 5', 'Sony', 'CONSOLE', 499.99, 'Next-gen gaming console with fast load times', 'https://picsum.photos/seed/ps5/300'),
('Xbox Series X', 'Microsoft', 'CONSOLE', 499.99, 'Powerful gaming console with Game Pass support', 'https://picsum.photos/seed/xboxseriesx/300'),
('Apple Watch Series 8', 'Apple', 'WEARABLE', 399.99, 'Smartwatch with health and fitness tracking', 'https://picsum.photos/seed/applewatch8/300'),
('Galaxy Watch 5', 'Samsung', 'WEARABLE', 349.99, 'Android-compatible smartwatch with sleek design', 'https://picsum.photos/seed/galaxywatch5/300'),
('Dell XPS 13', 'Dell', 'LAPTOP', 1099.99, 'Compact laptop with InfinityEdge display', 'https://picsum.photos/seed/dellxps13/300'),
('Bose QuietComfort 45', 'Bose', 'HEADPHONES', 329.99, 'Comfortable headphones with top-tier ANC', 'https://picsum.photos/seed/boseqc45/300'),
('Razer Blade 15', 'Razer', 'LAPTOP', 1899.99, 'Gaming laptop with high refresh rate display', 'https://picsum.photos/seed/razerblade15/300'),
('Google Nest Hub', 'Google', 'SMART_HOME', 99.99, 'Smart display with Google Assistant built-in', 'https://picsum.photos/seed/nesthub/300'),
('Echo Show 8', 'Amazon', 'SMART_HOME', 129.99, 'Smart speaker with display and Alexa', 'https://picsum.photos/seed/echoshow8/300'),
('Fitbit Charge 5', 'Fitbit', 'WEARABLE', 179.99, 'Fitness tracker with built-in GPS', 'https://picsum.photos/seed/fitbitcharge5/300'),
('OnePlus 11', 'OnePlus', 'SMARTPHONE', 729.99, 'Flagship phone with fast charging and performance', 'https://picsum.photos/seed/oneplus11/300'),
('ASUS ROG Phone 6', 'ASUS', 'SMARTPHONE', 999.99, 'Gaming smartphone with high refresh rate display', 'https://picsum.photos/seed/asusrog6/300'),
('HP Spectre x360', 'HP', 'LAPTOP', 1349.99, '2-in-1 premium laptop with stylus support', 'https://picsum.photos/seed/hpspectrex360/300'),
('Lenovo Tab P11 Pro', 'Lenovo', 'TABLET', 499.99, 'Android tablet with OLED display', 'https://picsum.photos/seed/lenovotabp11/300'),
('DJI Mini 3 Pro', 'DJI', 'CAMERA', 759.99, 'Lightweight drone with 4K camera', 'https://picsum.photos/seed/djimini3pro/300'),
('GoPro Hero 11', 'GoPro', 'CAMERA', 399.99, 'Action camera with advanced stabilization', 'https://picsum.photos/seed/goprohero11/300'),
('Nintendo Switch OLED', 'Nintendo', 'CONSOLE', 349.99, 'Hybrid gaming console with OLED display', 'https://picsum.photos/seed/nintendooled/300');
